name: Waka Readme

on:
  schedule:
    # Runs at 7:30 PM UTC daily, which is 11:30 AM PST
    - cron: '30 19 * * *'  
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
